# Generated by Django 2.1 on 2019-06-19 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Pewne imie klienta')),
                ('telephone', models.IntegerField(verbose_name='Telefon klienta')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.SmallIntegerField(verbose_name='Numer roli')),
                ('role', models.CharField(max_length=50, verbose_name='Rola użytkownika')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user/image', verbose_name='Obraz użytkownika')),
                ('birth_day', models.DateField(blank=True, verbose_name='Data urodzenia')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Role', verbose_name='Rola użytkownika')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_extras_data', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik, do którego odnoszą się dane')),
            ],
        ),
        migrations.CreateModel(
            name='UserSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa linku społecznościowego')),
                ('link', models.URLField(verbose_name='Link społecznościowy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='Użytkownik, którego dotyczy link')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Role', verbose_name='Rola klienta'),
        ),
    ]
