# Generated by Django 2.2.1 on 2019-06-01 08:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('img', models.ImageField(default='', upload_to='static/images/')),
                ('social', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.SmallIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 6, 1, 8, 12, 16, 282539, tzinfo=utc))),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('barber', models.ManyToManyField(to='services.Barber')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('telephone', models.IntegerField()),
                ('barber', models.ManyToManyField(to='services.Barber')),
                ('reservation_day', models.ManyToManyField(to='services.ReservationDate')),
            ],
        ),
    ]
