# Generated by Django 2.2.1 on 2019-06-01 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='static/images/')),
                ('icon', models.ImageField(upload_to='static/images/')),
                ('price', models.FloatField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 6, 1, 8, 54, 27, 920899, tzinfo=utc)),
        ),
    ]
