# Generated by Django 2.2.1 on 2019-06-02 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190601_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 6, 2, 14, 51, 3, 752053, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shortcuts', models.CharField(max_length=10)),
                ('is_working', models.SmallIntegerField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Barber')),
            ],
        ),
    ]
