# Generated by Django 2.2.1 on 2019-06-02 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190602_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='img',
            new_name='big_img',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='barber',
            new_name='barbers',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='reservation_day',
            new_name='reservation_days',
        ),
        migrations.RenameField(
            model_name='day',
            old_name='shortcuts',
            new_name='shortcut',
        ),
        migrations.RenameField(
            model_name='reservationdate',
            old_name='barber',
            new_name='barbers',
        ),
        migrations.AddField(
            model_name='barber',
            name='small_img',
            field=models.ImageField(default='', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 6, 2, 15, 11, 31, 305413, tzinfo=utc)),
        ),
    ]
