# Generated by Django 2.2.1 on 2019-06-03 04:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190602_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_nr',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 6, 3, 4, 47, 40, 221218, tzinfo=utc)),
        ),
    ]
