# Generated by Django 2.2.1 on 2019-06-03 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190603_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day_nr',
            new_name='week_day_nr',
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 6, 3, 7, 56, 46, 400925, tzinfo=utc)),
        ),
    ]
