# Generated by Django 2.2.1 on 2019-06-03 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190603_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='is_working',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 6, 3, 14, 33, 55, 59793, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('status', models.SmallIntegerField(default=0)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Day')),
            ],
        ),
    ]
