# Generated by Django 2.2.1 on 2019-06-03 20:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190603_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.DateField(auto_now=True, verbose_name=datetime.date(2019, 6, 3)),
        ),
        migrations.AddField(
            model_name='day',
            name='month_day_nr',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 6, 3, 20, 12, 53, 431683, tzinfo=utc)),
        ),
    ]
