# Generated by Django 2.2.1 on 2019-06-03 20:25

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20190603_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 6, 3, 20, 25, 28, 951127, tzinfo=utc)),
        ),
    ]
