# Generated by Django 2.2.1 on 2019-06-03 20:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20190603_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='month',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='day',
            name='month_day_nr',
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 6, 3, 20, 35, 25, 176588, tzinfo=utc)),
        ),
    ]
