# Generated by Django 2.2.1 on 2019-06-04 05:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20190603_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 6, 4, 5, 43, 30, 288380, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='BarberDaysSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shortcut', models.CharField(max_length=10)),
                ('week_day_nr', models.SmallIntegerField(default=0)),
                ('status', models.SmallIntegerField(default=0)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Barber')),
            ],
        ),
    ]
