# Generated by Django 2.2.1 on 2019-06-04 06:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20190604_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='day_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.BarberDaysSetting'),
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 6, 4, 6, 7, 35, 528282, tzinfo=utc)),
        ),
    ]
