# Generated by Django 2.2.1 on 2019-06-04 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20190604_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_working_days', models.SmallIntegerField(default=7)),
            ],
        ),
        migrations.AlterField(
            model_name='reservationdate',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2019, 6, 4, 8, 43, 49, 259253, tzinfo=utc)),
        ),
    ]
