# Generated by Django 2.1 on 2019-06-19 13:56

import barbershop.apps.service.assistants
import barbershop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nazwa usługi')),
                ('slug', models.CharField(blank=True, max_length=255, validators=[barbershop.validators.prohibited_slug_validator, barbershop.validators.format_slug_validator], verbose_name='Slug usługi')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Słowa kluczowe SEO')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Opis SEO')),
                ('description', models.CharField(max_length=255, verbose_name='Opis usługi')),
                ('price', models.FloatField(max_length=10, null=True, verbose_name='Cena usługi')),
                ('button', models.CharField(max_length=20, verbose_name='Napis na przycisku')),
                ('image', models.ImageField(blank=True, upload_to='service/image/', verbose_name='Zdjecie usługi')),
                ('icon', models.ImageField(blank=True, upload_to='service/icon/', verbose_name='Ikona usługi')),
                ('status', models.BooleanField(default=False, verbose_name='Czy opublikowana usługa')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia usługi')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data zmiany usługi')),
            ],
            bases=(models.Model, barbershop.apps.service.assistants.ServiceAssistant),
        ),
    ]
