# Generated by Django 2.1 on 2019-06-18 14:22

import barbershop.apps.service.assistants
import barbershop.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Pewne imie fryziera')),
                ('description', models.TextField(blank=True, verbose_name='Opis fryzjera')),
                ('big_img', models.ImageField(default='', upload_to='barber/image/', verbose_name='Duze zdjecie fryzjera')),
                ('small_img', models.ImageField(default='', upload_to='barber/icon/', verbose_name='Male zdjecie fryzjera')),
                ('social', models.CharField(blank=True, max_length=150, verbose_name='Linki fryzjera')),
            ],
        ),
        migrations.CreateModel(
            name='BarberDaysSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Dzien')),
                ('shortcut', models.CharField(max_length=10, verbose_name='Skrot')),
                ('week_day_nr', models.SmallIntegerField(default=0, verbose_name='Numer dnia w tygodniu')),
                ('status', models.SmallIntegerField(default=0, verbose_name='Czy jest roboczy')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Barber', verbose_name='Fryzjer, ktorego dotyczy dzien')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Pewne imie clienta')),
                ('telephone', models.IntegerField(verbose_name='Telefon clienta')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Dzien')),
                ('shortcut', models.CharField(max_length=10, verbose_name='Skrot')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data dnia')),
                ('week_day_nr', models.SmallIntegerField(default=0, verbose_name='Numer dnia w tygodniu')),
                ('status', models.SmallIntegerField(verbose_name='Czy jest roboczy')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Barber', verbose_name='Fryzjer, ktorego dotyczy dzien')),
                ('day_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.BarberDaysSetting', verbose_name='Ustawienia dnia')),
            ],
            bases=(models.Model, barbershop.apps.service.assistants.DayAssistant),
        ),
        migrations.CreateModel(
            name='ReservationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data rezerwacji')),
                ('status', models.SmallIntegerField(default=0, verbose_name='Status rezervacji')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data zmiany')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Barber', verbose_name='Fryzjer, ktorego dotyczy data')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Client', verbose_name='Client, ktorego dotyczy data')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nazwa usługi')),
                ('slug', models.CharField(blank=True, max_length=255, validators=[barbershop.validators.prohibited_slug_validator, barbershop.validators.format_slug_validator], verbose_name='Slug usługi')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Słowa kluczowe SEO')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Opis SEO')),
                ('description', models.CharField(max_length=255, verbose_name='Opis usługi')),
                ('price', models.FloatField(max_length=10, null=True, verbose_name='Cena usługi')),
                ('image', models.ImageField(blank=True, upload_to='service/image/', verbose_name='Zdjecie usługi')),
                ('icon', models.ImageField(blank=True, upload_to='service/icon/', verbose_name='Ikona usługi')),
                ('status', models.BooleanField(default=False, verbose_name='Czy opublikowana usługa')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia usługi')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data zmiany usługi')),
            ],
            bases=(models.Model, barbershop.apps.service.assistants.ServiceAssistant),
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_working_days', models.SmallIntegerField(default=7, verbose_name='Nazwa usługi')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(verbose_name='Godzina')),
                ('status', models.SmallIntegerField(default=1, verbose_name='Czy nie jest zajeta')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Day', verbose_name='Dzien, ktorego dotyczy gogzina')),
            ],
        ),
    ]
