# Generated by Django 2.1 on 2019-06-15 23:42

import barbershop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='big_img',
            field=models.ImageField(default='', upload_to='barber/image/', verbose_name='Duze zdjecie fryzjera'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='small_img',
            field=models.ImageField(default='', upload_to='barber/icon/', verbose_name='Male zdjecie fryzjera'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, upload_to='service/icon/', verbose_name='Ikona usługi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='service/image/', verbose_name='Zdjecie usługi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(max_length=10, null=True, verbose_name='Cena usługi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=255, validators=[barbershop.validators.prohibited_slug_validator, barbershop.validators.format_slug_validator], verbose_name='Slug usługi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nazwa usługi'),
        ),
    ]
