# Generated by Django 2.1 on 2019-06-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Czy wyświetlone na stronie'),
        ),
    ]
