# Generated by Django 2.1 on 2019-06-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190615_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nazwa usługi'),
        ),
    ]
