# Generated by Django 2.1 on 2019-06-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190613_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(max_length=150, unique=True, verbose_name='Slug usługi'),
        ),
    ]
