# Generated by Django 2.1 on 2019-06-16 13:06

import barbershop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20190616_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=255, validators=[barbershop.validators.prohibited_slug_validator, barbershop.validators.format_slug_validator], verbose_name='Slug usługi'),
        ),
    ]
