# Generated by Django 2.1 on 2019-06-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20190614_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(blank=True, max_length=10, verbose_name='Cena usługi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Slug usługi'),
        ),
    ]
