# Generated by Django 2.1 on 2019-06-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20190615_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(max_length=10, null=True, verbose_name='Cena usługi'),
        ),
    ]
