# Generated by Django 2.1 on 2019-06-15 15:48

import barbershop.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20190615_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[barbershop.validators.prohibited_slug_validator, django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$', 'Nieprawidłowy format slug')], verbose_name='Slug usługi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nazwa usługi'),
        ),
    ]
