# Generated by Django 2.1 on 2019-06-15 15:58

import barbershop.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20190615_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, validators=[barbershop.validators.prohibited_slug_validator, django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$', 'Nieprawidłowy format slug')], verbose_name='Slug usługi'),
        ),
    ]
