# Generated by Django 2.1 on 2019-06-15 16:40

import barbershop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20190615_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, validators=[barbershop.validators.prohibited_slug_validator, barbershop.validators.slug_validate], verbose_name='Slug usługi'),
        ),
    ]
