# Generated by Django 2.1 on 2019-06-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20190617_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Opis CEO'),
        ),
    ]
