# Generated by Django 2.1 on 2019-06-20 05:45

import barbershop.apps.barber.assistants
import barbershop.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Pewne imie fryziera')),
                ('slug', models.CharField(blank=True, max_length=150, validators=[barbershop.validators.prohibited_slug_validator, barbershop.validators.format_slug_validator], verbose_name='Slug fryziera')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Słowa kluczowe SEO')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='Opis SEO')),
                ('description', models.TextField(verbose_name='Opis fryzjera')),
                ('image', models.ImageField(blank=True, upload_to='barber/image/', verbose_name='Duze zdjecie fryzjera')),
                ('icon', models.ImageField(blank=True, upload_to='barber/icon/', verbose_name='Male zdjecie fryzjera')),
                ('status', models.BooleanField(default=False, verbose_name='Czy wyświetlone na stronie')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia fryzjera')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data zmiany fryzjera')),
            ],
            bases=(models.Model, barbershop.apps.barber.assistants.BarberAssistant),
        ),
        migrations.CreateModel(
            name='BarberSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nazwa umiejętności fryzjera')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Poziom umiejętności')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.Barber', verbose_name='Fryzjer, którego dotyczy nawyk')),
            ],
        ),
        migrations.CreateModel(
            name='BarberSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nazwa linku społecznościowego')),
                ('link', models.URLField(verbose_name='Link społecznościowy')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.Barber', verbose_name='Fryzjer, którego dotyczy link')),
            ],
        ),
    ]
