# Generated by Django 2.1 on 2019-06-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_auto_20190619_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Pewne imie fryziera'),
        ),
    ]
