# Generated by Django 2.1 on 2019-06-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0004_auto_20190619_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='name',
            new_name='title',
        ),
    ]
