# Generated by Django 2.1 on 2019-06-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0005_auto_20190619_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='icon',
            field=models.ImageField(blank=True, upload_to='barber/icon/', verbose_name='Male zdjecie fryzjera'),
        ),
        migrations.AlterField(
            model_name='barber',
            name='image',
            field=models.ImageField(blank=True, upload_to='barber/image/', verbose_name='Duze zdjecie fryzjera'),
        ),
    ]
