# Generated by Django 2.1 on 2019-06-20 05:45

import barbershop.apps.calendar.assistants
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barber', '0001_initial'),
        ('setting', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Nazwa dnia')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data dnia')),
                ('is_working', models.BooleanField(default=True, verbose_name='Czy jest roboczy')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.Barber', verbose_name='Fryzjer, ktorego dotyczy dzien')),
                ('day_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setting.BarberDaysSetting', verbose_name='Ustawienia dnia')),
            ],
            bases=(models.Model, barbershop.apps.calendar.assistants.DayAssistant),
        ),
        migrations.CreateModel(
            name='ReservationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data rezerwacji')),
                ('confirmed', models.BooleanField(default=True, verbose_name='Czy rezerwacja została potwierdzona')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Data zmiany')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.Barber', verbose_name='Fryzjer, ktorego dotyczy data')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Client', verbose_name='Klient, ktorego dotyczy data')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(verbose_name='Godzina')),
                ('is_busy', models.BooleanField(default=False, verbose_name='Czy godzina jest zajeta')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar.Day', verbose_name='Dzien, ktorego dotyczy gogzina')),
            ],
        ),
    ]
