# Generated by Django 2.1 on 2019-06-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('barber', '0001_initial'),
        ('calendar', '0002_auto_20190626_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='barber',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='barber.Barber', verbose_name='Fryzjer, ktorego dotyczy wydarzenie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.Service', verbose_name='Usluga, ktorej dotyczy wydarzenie'),
            preserve_default=False,
        ),
    ]
