# Generated by Django 2.1 on 2019-06-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_auto_20190627_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_settings',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='setting.BarberDaysSetting', verbose_name='Ustawienia dnia'),
            preserve_default=False,
        ),
    ]
