# Generated by Django 2.1 on 2019-06-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberDaysSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Dzien')),
                ('shortcut', models.CharField(max_length=10, verbose_name='Skrot')),
                ('week_day_nr', models.SmallIntegerField(default=0, verbose_name='Numer dnia w tygodniu')),
                ('is_working', models.BooleanField(default=False, verbose_name='Czy jest roboczy')),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.Barber', verbose_name='Fryzjer, ktorego dotyczy dzien')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_working_days', models.SmallIntegerField(default=7, verbose_name='Nazwa usługi')),
            ],
        ),
    ]
