# Generated by Django 2.1 on 2019-06-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nazwa statusu')),
                ('number', models.IntegerField(verbose_name='Numer statusu')),
                ('status_class', models.CharField(max_length=50, verbose_name='Style statusu')),
                ('text_color', models.CharField(max_length=50, verbose_name='Kolor nadpisu')),
                ('background_color', models.CharField(max_length=50, verbose_name='Kolor tła')),
                ('border_color', models.CharField(max_length=50, verbose_name='Kolor ramki')),
            ],
        ),
        migrations.AlterField(
            model_name='barberdayssetting',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='barber.Barber', verbose_name='Fryzjer, ktorego dotyczy dzien'),
        ),
    ]
