# Generated by Django 2.1 on 2019-06-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20190626_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberdayssetting',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barber.Barber', verbose_name='Fryzjer, ktorego dotyczy dzien'),
        ),
    ]
