# Generated by Django 2.1 on 2019-06-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_auto_20190627_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberdayssetting',
            name='is_working',
            field=models.BooleanField(blank=True, default=False, verbose_name='Czy jest roboczy'),
        ),
    ]
